# Python coding through Numpy library
Authors: Elham Taghizadeh 

September 2023

# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy.

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [36]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [37]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [90]:
arr=np.array(my_list)
arr

array([1, 2, 3])

In [39]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
x=np.array(my_matrix)

# Similarly
we can create a three-dimensional ndarray as follows

In [41]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]])
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]])

In the code above, the function call creates ndarray with the passed
arguments. The first argument is a three- dimensional ndarray which has the data and the
second argument is the data type of the individual elements of the
ndarray. NumPy has quite a lot of data types.

# Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [92]:
#Get a value at an index
arr[1]

2

In [93]:
#Get values in a range
arr[1:3]

array([2, 3])

In [94]:
#Get values in a range
arr[==

array([1, 2, 3])

# Indexing a 2D array (matrices)

The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend using the comma notation for clarity.


In [95]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [96]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [97]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [98]:
# Getting individual element value
arr_2d[1,0]

20

In [99]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [100]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [101]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

We can access individual members of three-dimensional arrays as
follows

In [102]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]])

In [42]:
(x [1, 1, 2])

-5

In [43]:
(x[:, 1, 1])

array([ 5, -4])

In [44]:
(x.shape)

(2, 2, 3)

In [45]:
(x.ndim)

3

In [46]:
(x.dtype)

dtype('int32')

In [47]:
(x.size)

12

In [48]:
(x.T)

array([[[ 1,  0],
        [ 4, -3]],

       [[ 2, -1],
        [ 5, -4]],

       [[ 3, -2],
        [ 6, -5]]])

You can also use a nested for loop like shown below

In [49]:
n = 3
arr = []
for x in range(n):
    arr.append([])
    for y in range(n):
        arr[x].append([])
        for z in range(n):
            arr[x][y].append(0)
print(arr)

[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]


## Built-in Methods

There are lots of built-in ways to generate arrays.

### zeros, ones, empty, eye and identity

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]
Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [51]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.ones(3)

array([1., 1., 1.])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.empty([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.identity(5, dtype= np.uint8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

# Array broadcastion with scalars


In [57]:
A=np.ones((3,3))
print(3*A-1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# Vector operations


In [115]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [107]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Users\West\AppData\Local\Temp\ipykernel_3732\205474414.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Users\West\AppData\Local\Temp\ipykernel_3732\616699925.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [109]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [58]:
#note: numpy automatically converts lists
u=[1,2,3,4]
v=[-1,2,5,6]
w1=np.inner(u,v)
w2=np.outer(u,v)
w3=np.dot(u,v)
print(w1,w2,w3)

42 [[-1  2  5  6]
 [-2  4 10 12]
 [-3  6 15 18]
 [-4  8 20 24]] 42


# Matrix operations

In [59]:
A=np.ones((3,2))
B=np.ones((2,3))
C=np.dot(A,B)
D=np.dot(B,A)
print(C,D)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] [[3. 3.]
 [3. 3.]]


# Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [110]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [111]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [112]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [113]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\West\AppData\Local\Temp\ipykernel_3732\2367246271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# arange
arange() function creates a series of numbers. Its use is as follows
Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [60]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# linspace


Similar to range(), we have linspace() that takes upper limit, lower limit, and number of points for an ndarray as follows


In [62]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [63]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [64]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [65]:
np.random.rand(2)

array([0.84473943, 0.46661302])

In [66]:
np.random.rand(5,5)

array([[0.60178388, 0.86648406, 0.31143497, 0.61956449, 0.6877709 ],
       [0.99737984, 0.73417311, 0.61331742, 0.00326276, 0.71201089],
       [0.72828216, 0.02919488, 0.45700618, 0.69626041, 0.64068877],
       [0.83254078, 0.03783104, 0.89417133, 0.49780974, 0.4098009 ],
       [0.45629368, 0.82576714, 0.30613023, 0.60327757, 0.7844292 ]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [67]:
np.random.randn(2)

array([-0.00313013, -0.51086406])

In [68]:
np.random.randn(5,5)

array([[-0.88855575, -1.10754035, -0.73730229,  1.1135482 , -0.33854464],
       [-1.20421244, -0.68266239, -1.00514379, -1.13389888,  0.75930171],
       [ 0.40208022, -1.18685538, -0.72692698, -1.08392303,  1.03657173],
       [ 0.11935966, -1.61155097, -0.56485154, -0.2713071 ,  0.5836096 ],
       [-0.26703138,  0.02092194,  3.03913234, -0.45683973,  1.47353046]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [69]:
np.random.randint(1,100)

4

In [70]:
np.random.randint(1,100,10)

array([23, 99, 52, 52, 87, 75, 42, 66, 38, 73])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [71]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [72]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [73]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [76]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [77]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [78]:
ranarr.max()

39

In [79]:
ranarr.argmax()

7

In [80]:
ranarr.min()

2

In [81]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [82]:
# Vector
arr.shape

(25,)

In [83]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
arr.reshape(1,25).shape

(1, 25)

In [85]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [86]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [87]:
arr.dtype

dtype('int32')

In [88]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Great Job!